name: 🚀 Deploy to Render on Push

on:
  push:
    branches:
      - main  # ya 'master', jo bhi tera default branch hai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Trigger Render Deploy
        uses: wei/curl@v1
        with:
          args: -X POST ${{ secrets.RENDER_HOOK_URL }}
