    - name: Test Gemini API Key Connection
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "Attempting to connect to Google Gemini API with provided key..."
        curl -X POST -H "Content-Type: application/json" \
             -d '{
                 "contents": [{
                     "parts": [{"text": "Hello, Gemini! Are you there?"}]
                 }],
                 "generationConfig": {
                     "temperature": 0.7
                 }
             }' \
             "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${{ env.GEMINI_API_KEY }}" \
             --fail --silent --show-error
        
        echo "\nGemini API Test completed. Check the output above for response or error."
